### ISSUE TITLE
Sending action command fails

### ISSUE THREAD

**Issue by Sidhesh-telsiz** [ncclient/ncclient#170]
Hi,
Is there an example which shows how to send action commands using ncclient.
Its one of the request commands which translate to action command.

Below is the snippet of my action command.
```
<action xmlns="http://tail-f.com/ns/netconf/actions/1.0">
 <data>
    <request xmlns="http://foo.com/actions">
    ---snip---
    </request>
 </data>
</action>
```
How do i send this to server using manager object.

**Comment by plajjan** [comment]
I wrangled the dispatch() function into calling an action by building the query myself.

I think your example is actually wrong, since that's now how the XML is or should be serialised. There is no `data` tag. See https://tools.ietf.org/html/rfc7950#page-116

Anyway, here's an example from my environment where I call `/infrastructure/backbone-interface[device='A'][interface='B']/self-test`

```
    rpc = new_ele_ns('action', 'urn:ietf:params:xml:ns:yang:1')
    rpc_in = sub_ele_ns(rpc, 'infrastructure', 'urn:telekom:terastream')
    rpc_di = sub_ele_ns(rpc_in, 'backbone-interface', 'urn:telekom:terastream')
    sub_ele_ns(rpc_di, 'device', 'urn:telekom:terastream').text = device
    sub_ele_ns(rpc_di, 'interface').text = interface
    sub_ele_ns(rpc_di, 'self-test').text = ''
    #print(etree.tostring(rpc))
    res = m.dispatch(rpc)
    print(etree.tostring(res.data))
    print(jxmlease.parse(etree.tostring(res.data))
```

m is the manager object, so just wrap the above code in the normal `with ... as m:`. I've used `sub_ele_ns` here, which is something I added as I didn't immediately see how else I could pick my own namespace when adding a sub element. You can see the commit, on my repo, here https://github.com/plajjan/ncclient/commit/8ab482b19c5135987f947de812eabc6077740dc2

In fact, when thinking about that, isn't it weird that sub_ele defaults to the BASE_NS_1_0 namespace instead of just using the parents namespace!?

Anyway, the response we get back includes the full path, like this
```
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <infrastructure xmlns="urn:telekom:terastream">
    <backbone-interface>
      <device>ne8-r2-5-1a-de</device>
      <interface>3/2/1</interface>
      <self-test>
        <success>true</success>
        ... snip snip, lots of output ...
      </self-test>
    </backbone-interface>
  </infrastructure>
</data>
```
whereas the RFC kind of indicates that the output should not be that deeply nested. My NETCONF server is NCS / NSO so not sure if they're doing something wrong or I am in my code (callback in NCS that is).

I wonder if we should document this in ncclient or provide a more convenient function (a modified dispatch perhaps). It would be much easier requesting with an XPath than all of this.

**Comment by Sidhesh-telsiz** [comment]
Thanks for the snippet @plajjan . 
I will try it out.

**Comment by leopoul** [comment]
Did that work?

**Comment by plajjan** [comment]
Just FYI, Tail-F has acked that the response they produce is incorrect and should not include the full path...
