### ISSUE TITLE
RPC Error

### ISSUE THREAD

**Issue by NetDevLazg** [ncclient/ncclient#322]
im using netconf to get the full configurations of one of my Cisco CSR 1000v and i get the bellow error message.

This is what i'm targeting: router_full_configs = m.get_config(source = "running")

**This is the error.**
RPCError: error: /oc-rpol:routing-policy/defined-sets/prefix-sets/prefix-set{EIGRP-ROUTES}/prefixes/prefix: badarg
error: /oc-rpol:routing-policy/defined-sets/prefix-sets/prefix-set{OSPF-ROUTES}/prefixes/prefix: badarg

**Comment by einarnn** [comment]
This is a bug in the IOS XE agent, and not an ncclient issue. Please raise an issue with Cisco TAC if you are able to. The issue is a bug in how Cisco support some parts of the openconfig model, which is mapped at the backend. When certain configurations are provisioned via CLI, bugs like this can manifest. When doing a get-config this can be avoided by looking at a specific XPath or sub tree filter, e.g. `/native` to retrieve main Cisco native model content.

**Comment by NetDevLazg** [comment]
Thanks for the quick reply @einarnn
