### ISSUE TITLE
self.timeout variable in class manager seems broken in v0.6.6 while using manager.connect_ssh(timeout=100) 

### ISSUE THREAD

**Issue by vipkum2** [ncclient/ncclient#325]
I am using manager in my script as:
`m = manager.connect_ssh(
            host=ip, 
            port=port, 
            username=user, 
            password=pwd, 
            hostkey_verify=False,
            timeout=100
        )`
This sets the m.timeout=100 till version 0.6.4. 
But now in version 0.6.6 this has no impact . I can only see m.timeout = 30 as this is default timeout  for class manager.

I have taken a look and found  below return statement in method connect_ssh may be causing the issue:
in v0.6.6:
 ` return Manager(session, device_handler, **manager_params)`
was as in 0.6.4:
 ` return Manager(session, device_handler, **kwds)`

**Comment by frepkovsky** [comment]
I faced the same issue. It is because in v0.6.6, since [commit 2a87ec0e8708b54164c2a49dbc60e6097484b88d](https://github.com/ncclient/ncclient/commit/2a87ec0e8708b54164c2a49dbc60e6097484b88d#diff-1b3c29288e0d70df2d14a7d41b118ddc) you have to specify _timeout_ parameter for Manager constructor in dictionary _manager_params_.

In your code example above, in v0.6.4:
`m = manager.connect_ssh( host=ip, port=port, username=user, password=pwd, hostkey_verify=False, timeout=100 )`

in v0.6.6, change to:
`m = manager.connect_ssh( host=ip, port=port, username=user, password=pwd, hostkey_verify=False, manager_params={'timeout': 100} )`

**Comment by vipkum2** [comment]
Thanks @frepkovsky ,

But we should avoid break any existing functionality.

**Comment by einarnn** [comment]
The change was allowed because the timeout was being used for two purposes. The first is a timeout for establishing the connection to the device, and the second being a timeout for specific operations. With the same parameter used for both operations, and it often being necessary for long-running operations to have a longer timeout, this inflexibility was causing issues. Unfortunately, rectifying such an inflexibility cannot leave all existing functionality in place.

If there is a significant body of opinion that this change should be rolled back, and the "old" timeout be applied to RPCs, and a new parameter applied to a timeout for establishing the SSH session, we can look at making this change.

Apologies for not making this change clearer in release notes.

**Comment by vipkum2** [comment]
Thanks @einarnn  for the nice explanation. I will update my suite accordingly.

**Comment by einarnn** [comment]
Ok. Closing this issue for now, but if there is any further concerns, please feel free to reopen.

**Comment by horseinthesky** [comment]
Hello.
Could you clarify this for me?
I have some code like this:
```
if __name__ == '__main__':
    with manager.connect(
        host=ca,
        port=22,
        timeout=10,
        ssh_config=True,
        username=getuser(),
        hostkey_verify=False,
        device_params={'name': 'junos'}
    ) as m:
```

I want to keep connection timeout as 10 sec but I need an RPC timeout as 45 sec.
How should I change the code?

**Comment by einarnn** [comment]
Try:

```
if __name__ == '__main__':
    with manager.connect(
        host=ca,
        port=22,
        timeout=10,
        ssh_config=True,
        username=getuser(),
        hostkey_verify=False,
        device_params={'name': 'junos'},
        manager_params={'timeout': 45}
    ) as m:
```

**Comment by horseinthesky** [comment]
> @horseinthesky, try:
> 
> ```
> if __name__ == '__main__':
>     with manager.connect(
>         host=ca,
>         port=22,
>         timeout=10,
>         ssh_config=True,
>         username=getuser(),
>         hostkey_verify=False,
>         device_params={'name': 'junos'},
>         manager_params={'timeout': 45}
>     ) as m:
> ```

Thank you. This works perfectly fine =)

**Comment by einarnn** [comment]
you're welcome!
