### ISSUE TITLE
delete config not working as expected

### ISSUE THREAD

**Issue by harshad1692** [ncclient/ncclient#445]
as per RFC 6241 in delete config has to give datastore, where it will delete configuration datastore but am getting error message.

**code** ```

with manager.connect(host=HOST, port=PORT, username=USER, password=PASS,hostkey_verify=False, device_params={'name': 'default'},look_for_keys=False, allow_agent=False) as m:
    assert(":validate"  in m.server_capabilities)
    c = m.delete_config(target='candidate')
    print("Running the test")
    print("Committing................")
    m.commit()

**output**
Traceback (most recent call last):
  File "user_mgmt_1.py", line 137, in <module>
    test_delete_config_1('candidate')
  File "user_mgmt_1.py", line 110, in test_delete_config_1
    c = m.delete_config(target=target)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/operations/edit.py", line 79, in request
    return self._request(node)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/operations/rpc.py", line 347, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: unknown object

what wrong am i doing or please guide me how can i delete config file

**Comment by einarnn** [comment]
The candidate data store should be discarded, not deleted. Use `m.discard_changes()` instead.

**Comment by fredgan** [comment]
Hi Einar @einarnn ,
AFAIK, the [delete-config](https://www.juniper.net/documentation/en_US/junos/topics/reference/tag-summary/netconf-delete-config.html) and [discard-changes](https://www.juniper.net/documentation/en_US/junos/topics/reference/tag-summary/netconf-discard-changes.html) operations are different.
`Delete config` deteles all configuration data in the existing candidate configuration or open configuration database.
Usage:
```
<rpc>
    <delete-config>
        <target>
            <candidate/>
        </target>
    </delete-config>
</rpc>
]]>]]>
```
`Discard changes` discards changes made to the candidate configuration and make its contents match the contents of the current running (active) configuration.
Usage:
```
<rpc>
    <discard-changes/>
</rpc>
]]>]]>
```
It should not report any errors because they both are legal.
Besides, according to [RFC 6241](https://tools.ietf.org/html/rfc6241#section-7.4), it means only running data can not be deleted.

**Comment by einarnn** [comment]
Don't you agree that the  candidate datastore is a proxy for the running configuration? It really isn't the same as, for example, the startup config, or the same as a configuration object at the end of a URL. Given its close association to the running config, I wouldn't expect a netconf agent to respect a `delete-config` operation against candidate as that would be near enough the same as supporting it against running, which RFC 6241 states is not allowed.

**Comment by einarnn** [comment]
Regardless, this isn't a problem with ncclient, so I am closing this issue! 🙂
