### ISSUE TITLE
juniper RPC should be XML Element

### ISSUE THREAD

**Issue by bmigette** [ncclient/ncclient#488]
The following file has issues:
https://github.com/ncclient/ncclient/blob/master/examples/juniper/execute-rpc-string.py
https://github.com/ncclient/ncclient/blob/master/examples/juniper/get-interface-status.py
(and possibly others)

`conn.rpc(rpc) `
should be
`conn.rpc(to_ele(rpc))`

Otherwise an error is thrown

**Comment by lzier** [comment]
It looks like this is a behavior change for Juniper RPCs (device_params={'name': 'junos'}) from ncclient version 0.6.9 (and earlier versions) to 0.6.10.

As a consequence every usage of Junos RPCs is broken and need to be changed when using 0.6.10.
I ran into the same problem today when I upgraded to 0.6.10 in the lab and Junos RPCs were not longer working.
Error message: device 1.1.1.1 failed with exception "Invalid tag name '<get-bgp-summary-information/>'"
As a workaround/fix like bmigette described:
from ncclient.xml_ import *
conn.rpc(to_ele(rpc))

Is this a wanted (why?!?; I found nothing in the changelog) or unwanted change (which will be fixed)?

**Comment by boxidau** [comment]
looks like this probably wasn't a desired change. Since the Juniper implementation provides an rpc method this is normally called via a __getattr__ lookup in the manager. 

https://github.com/ncclient/ncclient/pull/430 adds an rpc method directly to manager so __getattr__ is never called bypassing the juniper implementation of rpc

**Comment by einarnn** [comment]
This was unintentional. Addressed in #496.
